import os
import subprocess
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

# ==============================================================================
# 1. NGSPICE RAW PARSER (From cicsim)
# ==============================================================================
BSIZE_SP = 512
MDATA_LIST =[b'title', b'date', b'plotname', b'flags', b'no. variables',
              b'no. points', b'dimensions', b'command', b'option']

def ngRawRead(fname: str):
    fp = open(fname, 'rb')
    plot = {}
    arrs = []
    plots =[]
    names = dict()
    ind = 0
    while (True):
        try:
            mdata = fp.readline(BSIZE_SP).split(b':', maxsplit=1)
        except:
            raise
        if len(mdata) == 2:
            if mdata[0].lower() in MDATA_LIST:
                plot[mdata[0].lower()] = mdata[1].strip()
            if mdata[0].lower() == b'variables':
                nvars = int(plot[b'no. variables'])
                npoints = int(plot[b'no. points'])
                plot['varnames'] = []
                plot['varunits'] =[]
                for varn in range(nvars):
                    varspec = (fp.readline(BSIZE_SP).strip()
                               .decode('ascii').split())
                    assert(varn == int(varspec[0]))
                    if(varspec[1] not in names):
                        names[varspec[1]] = 1
                    else:
                        varspec[1] += str(ind)
                        ind +=1
                    plot['varnames'].append(varspec[1])
                    plot['varunits'].append(varspec[2])
            if mdata[0].lower() == b'binary':
                rowdtype = np.dtype({'names': plot['varnames'],
                                     'formats':[np.complex128 if b'complex'
                                                 in plot[b'flags']
                                                 else np.float64]*nvars})
                arrs.append(np.fromfile(fp, dtype=rowdtype, count=npoints))
                plots.append(plot)
                fp.readline() 
        else:
            break
    fp.close()
    return (arrs, plots)

def toDataFrames(ngarr):
    (arrs, plots) = ngarr
    dfs = list()
    for i in range(0, len(plots)):
        # Fixed the index from 0 to i
        df = pd.DataFrame(data=arrs[i], columns=plots[i]['varnames'])
        dfs.append(df)
    return dfs

# ==============================================================================
# 2. USER CONFIGURATION
# ==============================================================================
# ---> TOGGLE THIS TO RUN SIMULATION OR JUST PLOT <---
RUN_SIMULATION = False

I0 = 100
kp = 266
VDD = 0.1
# TODO: Fill in your specific values below for the calculateAlpha function
VOH = 0.9*VDD      
VIH = 0.1*VDD      
n_n = 1.55       
n_p = 2.1       
phiT = 0.02585  # Thermal voltage at 27C

# The theoretical optimums you provided (used to center the grid)
# alpha_opt = 0.018599, beta_opt = 0.2292769, gamma_opt = 1.5746977

# Grid Search space: Sweeping the continuous math parameters
# We will bound them around your optimums.
beta_vals = np.logspace(-2, 1, 40)   
gamma_vals = np.logspace(-2, 1, 40) 

# --- 2. THE ALPHA EQUATION ---
def calculateAlpha(VDD, VOH, VIH, n_n, n_p, beta, gamma):
    NUM = beta * np.exp(VIH / (n_n * phiT)) * (
        (1 + beta * np.exp(-VOH / phiT) + gamma * np.exp((VOH - VIH) / (n_n * phiT)) * np.exp(-VOH / phiT)) /
        (1 + beta + gamma * np.exp((VOH - VIH) / (n_n * phiT)))
    )
    DEN = np.exp((VDD - VIH) / (n_p * phiT)) * (1 - np.exp((VOH - VDD) / phiT))
    return NUM / DEN

# --- 3. EXECUTION LOOP ---
if RUN_SIMULATION:
    results =[]
    os.makedirs("output_ac", exist_ok=True)

    for beta in beta_vals:
        for gamma in gamma_vals:
        
            # Calculate theoretical alpha
            alpha = calculateAlpha(VDD, VOH, VIH, n_n, n_p, beta, gamma)
            
            # Calculate actual physical (integer) transistor multipliers
            m_beta = max(1, round(beta * I0))
            m_gamma = max(1, round(gamma * I0))
            m_alpha = max(1, round(alpha * I0 * kp))
            
            # Write to SPICE include file
            with open("output_ac/sweep_params.spi", "w") as f:
                f.write(f"* Autogenerated by Grid Search\n")
                f.write(f".param m_alpha = {m_alpha}\n")
                f.write(f".param m_beta = {m_beta}\n")
                f.write(f".param m_gamma = {m_gamma}\n")
                
            # Run simulation using cicsim 'make typical'
            # Suppress stdout so it doesn't flood the terminal, but keep stderr for errors
            process = subprocess.run(["make", "typical"])
                
                
                
            # --- PARSE THE RAW FILE ---
            raw_file = "output_ac/ac_SchGtKttTtVt.raw" 
        
            if not os.path.exists(raw_file):
                print(f"  -> Error: No raw file found.")
                continue
            
            try:
                arrs, plots = ngRawRead(raw_file)
                dfs = toDataFrames((arrs, plots))
                df = dfs[0] 
                
                # Find i(vout) or i(VOUT) column name
                ivout_col = next(col for col in df.columns if 'i(vout)' in col.lower())
                
                # Since ac sweep ends exactly at 32768 Hz, extract the last value (.iloc[-1])
                i_vout_32k_c = df[ivout_col].iloc[-1]
                i_vout_32k_r = np.real(i_vout_32k_c)
                gm = i_vout_32k_r
                gm_masked = np.where(gm < 0, gm, np.nan)
                
                total_transistors = (I0 + m_beta + m_gamma + m_alpha)
                
                # Figure of Merit = gm / (Relative area)
                normalization = I0 + m_beta + m_gamma +4*m_alpha
                try:
                    fom = gm_masked / normalization
                except Exception:
                    fom = 0
                    
                results.append((beta, gamma, alpha, m_beta, m_gamma, m_alpha, gm, total_transistors, fom))
                print(f"  -> Success! gm={gm:.3e} | FoM={fom:.3e}")
            
                # Optionally delete raw file to save disk space over huge sweeps
                # os.remove(raw_file)
                
            except Exception as e:
                print(f"  -> Error parsing data: {e}")


    # --- 5. RESULTS AND VISUALIZATION ---
    columns =["beta_theory", "gamma_theory", "alpha_theory", "m_beta", "m_gamma", "m_alpha", "gm", "area", "fom"]
    df_res = pd.DataFrame(results, columns=columns)
    
    # Drop duplicate rows because different continuous beta/gamma might round to the same integer multipliers
    df_res_unique = df_res.drop_duplicates(subset=["m_beta", "m_gamma", "m_alpha"]).copy()
    df_res_unique.to_csv("grid_search_results.csv", index=False)
    print("\nResults saved to grid_search_results.csv")
    
else:
    # JUST LOAD THE DATA AND PLOT
    if not os.path.exists("grid_search_results.csv"):
        print("Error: 'grid_search_results.csv' not found.")
        print("Please set RUN_SIMULATION = True at the top of the script first!")
        exit()
        
    print("Loading data from grid_search_results.csv...")
    df_res_unique = pd.read_csv("grid_search_results.csv")


# ==============================================================================
# 5. RESULTS AND VISUALIZATION (Bypassing Matplotlib 3D Log Bug)
# ==============================================================================
best_design = df_res_unique.loc[df_res_unique['fom'].idxmin()]

print("\n" + "="*50)
print("BEST DESIGN (MAPPED TO THEORETICAL VALUES)")
print("="*50)
print(f"Theoretical : beta={best_design['beta_theory']:.4f}, gamma={best_design['gamma_theory']:.4f}, alpha={best_design['alpha_theory']:.4f}")
print(f"Multipliers : m_beta={best_design['m_beta']:.0f}, m_gamma={best_design['m_gamma']:.0f}, m_alpha={best_design['m_alpha']:.0f}")
print(f"Transconductance (gm) : {best_design['gm']:.3e} S")
print(f"Total Area Proxy      : {best_design['area']:.0f} transistors")
print(f"Max Figure of Merit   : {best_design['fom']:.3e}")

# Create a figure with two subplots
fig = plt.figure(figsize=(16, 7))

# -----------------------------------------------------------------------------
# METHOD 1: The 3D Workaround (Plot log10 data, label as floats)
# -----------------------------------------------------------------------------
ax1 = fig.add_subplot(121, projection='3d')

# Calculate base-10 logarithms of the THEORETICAL data
log_beta = np.log10(df_res_unique['beta_theory'])
log_gamma = np.log10(df_res_unique['gamma_theory'])

sc1 = ax1.scatter(log_beta, log_gamma, df_res_unique['fom']/232.9e-9, 
                  c=df_res_unique['fom']/232.9e-9, cmap='plasma', depthshade=True, s=40)

# Draw lines to indicate the location of the mininum
xmin = np.log10(best_design['beta_theory'])
ymin = np.log10(best_design['gamma_theory'])
z0 = best_design['fom']/232.9e-9
ax1.plot([np.log10(beta_vals).max(), xmin], [ymin, ymin], [z0, z0], color='blue', linestyle='--')
ax1.plot([xmin, xmin], [np.log10(gamma_vals).min(), ymin], [z0, z0], color='green', linestyle='--')

# Create a formatter function to change log values back to normal float text (e.g., 0.25, 1.5)
def log_tick_formatter(val, pos):
    return f"{10**val:.3g}"

#ax1.xaxis.set_major_formatter(ticker.FuncFormatter(log_tick_formatter))
#ax1.yaxis.set_major_formatter(ticker.FuncFormatter(log_tick_formatter))

ax1.set_xlabel(r'$log(\beta) = log(I_1/I_0)$', labelpad=15)
ax1.set_ylabel(r'$log(\gamma) = log(I_2/I_0)$', labelpad=15)
ax1.set_zlabel('FoM')
ax1.set_title('(a) 3D View: Figure of Merit')

# -----------------------------------------------------------------------------
# METHOD 2: 2D Scatter with Colormap (Best for Optimum Finding)
# -----------------------------------------------------------------------------
ax2 = fig.add_subplot(122)

# 2D plots handle native log scales flawlessly
sc2 = ax2.scatter(df_res_unique['beta_theory'], df_res_unique['gamma_theory'], 
                  c=df_res_unique['fom']/232.9e-9, cmap='plasma', s=30, edgecolors='black')

# Mark the optimum point with a big red star using theoretical coordinates
ax2.scatter(best_design['beta_theory'], best_design['gamma_theory'], 
            color='red', marker='x', s=250, label=r'Optimum: $\alpha$='+f'{best_design["alpha_theory"]:.3f}, '+r'$\beta$='+f'{best_design["beta_theory"]:.3f}, '+r'$\gamma$='+f'{best_design["gamma_theory"]:.3f}')

ax2.set_xscale('log')
ax2.set_yscale('log')

# Format ticks to show plain numbers instead of scientific notation
#ax2.xaxis.set_major_formatter(ticker.ScalarFormatter())
#ax2.yaxis.set_major_formatter(ticker.ScalarFormatter())

ax2.set_xlabel(r'$log(\beta) = log(I_1/I_0)$')
ax2.set_ylabel(r'$log(\gamma) = log(I_2/I_0)$')
ax2.yaxis.tick_right()
ax2.yaxis.set_label_position("right")
ax2.set_title('(b) Heatmap View: Figure of Merit')
ax2.grid(True, which="both", ls="--", alpha=0.5)
ax2.legend()

# Add a shared colorbar
cbar = fig.colorbar(sc2, ax=[ax1, ax2], pad=0.08, aspect=30)
cbar.set_label('Figure of Merit (FoM)')

plt.show()


