import os
import glob
import subprocess
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ==============================================================================
# 1. NGSPICE RAW PARSER (From cicsim)
# ==============================================================================
BSIZE_SP = 512
MDATA_LIST =[b'title', b'date', b'plotname', b'flags', b'no. variables',
              b'no. points', b'dimensions', b'command', b'option']

def ngRawRead(fname: str):
    fp = open(fname, 'rb')
    plot = {}
    arrs =[]
    plots =[]
    names = dict()
    ind = 0
    while (True):
        try:
            mdata = fp.readline(BSIZE_SP).split(b':', maxsplit=1)
        except:
            raise
        if len(mdata) == 2:
            if mdata[0].lower() in MDATA_LIST:
                plot[mdata[0].lower()] = mdata[1].strip()
            if mdata[0].lower() == b'variables':
                nvars = int(plot[b'no. variables'])
                npoints = int(plot[b'no. points'])
                plot['varnames'] = []
                plot['varunits'] =[]
                for varn in range(nvars):
                    varspec = (fp.readline(BSIZE_SP).strip().decode('ascii').split())
                    assert(varn == int(varspec[0]))
                    if(varspec[1] not in names):
                        names[varspec[1]] = 1
                    else:
                        varspec[1] += str(ind)
                        ind +=1
                    plot['varnames'].append(varspec[1])
                    plot['varunits'].append(varspec[2])
            if mdata[0].lower() == b'binary':
                rowdtype = np.dtype({'names': plot['varnames'],
                                     'formats':[np.complex128 if b'complex'
                                                 in plot[b'flags']
                                                 else np.float64]*nvars})
                arrs.append(np.fromfile(fp, dtype=rowdtype, count=npoints))
                plots.append(plot)
                fp.readline() 
        else:
            break
    fp.close()
    return (arrs, plots)

def toDataFrames(ngarr):
    (arrs, plots) = ngarr
    dfs = list()
    for i in range(0, len(plots)):
        df = pd.DataFrame(data=arrs[i], columns=plots[i]['varnames'])
        dfs.append(df)
    return dfs


# ==============================================================================
# 2. USER CONFIGURATION
# ==============================================================================
RUN_SIMULATION = True

# The exact terminal command you use to trigger the ETC sweep.
# E.g., ["make", "etc"] or ["cicsim", "run", "ac", "etc"]
SIM_COMMAND =["make", "etc"]

# ==============================================================================
# 3. EXECUTION LOOP
# ==============================================================================
if RUN_SIMULATION:
    os.makedirs("output_ac", exist_ok=True)
    
    # Load parameters, ignoring spaces after commas
    # sizes = pd.read_csv("vdd_gm_sweep_sizes.csv", skipinitialspace=True)
    sizes = pd.read_csv("vdd_gm_sweep_1size.csv", skipinitialspace=True)
    sizes.columns = sizes.columns.str.replace('"', '') 
    
    vdd_list = []
    gm_dict =  {"Kss": {"Tl":[],"Th":[]}, "Kff": {"Tl":[],"Th":[]}, "Ksf": {"Tl":[],"Th":[]}, "Kfs": {"Tl":[],"Th":[]}}

    print(f"Starting ETC Sweep ({len(sizes)} designs)...")
    for row in sizes.itertuples(index=False):
        VDD = row.VDD
        m_alpha = int(row.P0)
        m_I0 = int(row.N0)
        m_beta = int(row.N1)
        m_gamma = int(row.N2)

        vdd_list.append(VDD)

        # 1. Write the parameters
        with open("output_ac/sweep_sizes.spi", "w") as f:
            f.write(f"* Autogenerated by Grid Search\n")
            f.write(f".param AVDD = {VDD}\n")
            f.write(f".param m_I0 = {m_I0}\n")
            f.write(f".param m_alpha = {m_alpha}\n")
            f.write(f".param m_beta = {m_beta}\n")
            f.write(f".param m_gamma = {m_gamma}\n")

        # 2. Clean up ANY old .raw files so we don't mix up runs
        old_raw_files = glob.glob("output_ac/*.raw")
        for old_file in old_raw_files:
            os.remove(old_file)

        # 3. Run the Monte Carlo Simulation
        print(f"Running ETC for VDD = {VDD:.3f}V ...", end="", flush=True)
        subprocess.run(SIM_COMMAND)

        # 4. Find all newly generated .raw files
        new_raw_files = glob.glob("output_ac/*.raw")

        if not new_raw_files:
            print(" Error: No .raw files were generated!")
            continue
        
        # 5. Extract data robustly (handles 1 giant raw file OR 30 split raw files)
        for raw_file in new_raw_files:
            try:
                # Extract the corner
                idx_K = raw_file.index("K")
                corner = raw_file[idx_K:idx_K+3]
                # Extract temp corner
                idx_T = raw_file.index("T")
                temp_corner = raw_file[idx_T:idx_T+2]
                # Get data
                arrs, plots = ngRawRead(raw_file)
                dfs = toDataFrames((arrs, plots))
                
                # Some raw files have multiple Monte Carlo plots inside them
                for df in dfs:
                    ivout_col = next(col for col in df.columns if 'i(vout)' in col.lower())
                    
                    # Extract last frequency point, isolate Real part, invert sign
                    i_vout_32k = df[ivout_col].iloc[-1]
                    gm_val = -np.real(i_vout_32k)
                    gm_dict[corner][temp_corner].append(gm_val)
            except Exception as e:
                print(f" (Error parsing {raw_file}: {e})", end="")
                
        
        print(f" Done!")


    # Save summary data so you can tweak the plot later without re-simulating!
    df_summary = pd.DataFrame({'VDD': vdd_list, 'Kss_Tl': gm_dict["Kss"]["Tl"], 'Kff_Tl': gm_dict["Kff"]["Tl"], 'Ksf_Tl': gm_dict["Ksf"]["Tl"], 'Kfs_Tl': gm_dict["Kfs"]["Tl"], 'Kss_Th': gm_dict["Kss"]["Th"], 'Kff_Th': gm_dict["Kff"]["Th"], 'Ksf_Th': gm_dict["Ksf"]["Th"], 'Kfs_Th': gm_dict["Kfs"]["Th"]})
    df_summary.to_csv("etc_summary_results.csv", index=False)
    print("\nSimulation sweep complete. Data saved to etc_summary_results.csv")

else:
    # If RUN_SIMULATION = False, just load the existing summary
    if not os.path.exists("etc_summary_results.csv"):
        print("Error: etc_summary_results.csv not found. Set RUN_SIMULATION = True first.")
        exit()
        
    df_summary = pd.read_csv("etc_summary_results.csv")
    pd.set_option('display.precision', 8)  # Number of decimal places
    print(df_summary)
    vdd_list = df_summary['VDD'].values
    gm_dict =  {"Kss": {"Tl":df_summary['Kss_Tl'],"Th":df_summary['Kss_Th']}, "Kff": {"Tl":df_summary['Kff_Tl'],"Th":df_summary['Kff_Th']}, "Ksf": {"Tl":df_summary['Ksf_Tl'],"Th":df_summary['Ksf_Th']}, "Kfs": {"Tl":df_summary['Kfs_Tl'],"Th":df_summary['Kfs_Th']}}


# ==============================================================================
# 4. PLOTTING THE MONTE CARLO RESULTS
# ==============================================================================
vdd_arr = np.array(vdd_list)

fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=(10, 6))

for T in ["Tl", "Th"]:
    if T == "Tl":
        ax = ax1
    else:
        ax = ax2
        
    palette = {"Kss": 'blue', "Kff": 'red', "Ksf": 'green', "Kfs": 'magenta'}
    shade_palette = {"Kss": 'lightblue', "Kff": 'salmon', "Ksf": 'mediumseagreen', "Kfs": 'orchid'}
    for corner in gm_dict.keys():
        # Plot the mean line
        ax.plot(vdd_arr, gm_dict[corner][T], color=palette[corner], marker='o', linestyle='-', linewidth=2, label=corner)

# Formatting the plot
ax1.set_title('T = -40 °C', fontsize=14)
ax2.set_title('T = 125 °C', fontsize=14)
ax1.set_xlabel('VDD [Volts]', fontsize=12)
ax2.set_xlabel('VDD [Volts]', fontsize=12)
ax1.set_ylabel('Transconductance ($g_m$) [S]', fontsize=12)
ax2.set_ylabel('Transconductance ($g_m$) [S]', fontsize=12)

# Make axes use scientific notation cleanly
ax1.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
ax2.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
ax1.grid(True, which='both', linestyle='--', alpha=0.6)
ax2.grid(True, which='both', linestyle='--', alpha=0.6)
ax1.legend(loc='upper left', fontsize=12)
ax2.legend(loc='upper left', fontsize=12)

plt.tight_layout()
plt.show()
