import os
import subprocess
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

# ==============================================================================
# 1. NGSPICE RAW PARSER (From cicsim)
# ==============================================================================
BSIZE_SP = 512
MDATA_LIST =[b'title', b'date', b'plotname', b'flags', b'no. variables',
              b'no. points', b'dimensions', b'command', b'option']

def ngRawRead(fname: str):
    fp = open(fname, 'rb')
    plot = {}
    arrs = []
    plots =[]
    names = dict()
    ind = 0
    while (True):
        try:
            mdata = fp.readline(BSIZE_SP).split(b':', maxsplit=1)
        except:
            raise
        if len(mdata) == 2:
            if mdata[0].lower() in MDATA_LIST:
                plot[mdata[0].lower()] = mdata[1].strip()
            if mdata[0].lower() == b'variables':
                nvars = int(plot[b'no. variables'])
                npoints = int(plot[b'no. points'])
                plot['varnames'] = []
                plot['varunits'] =[]
                for varn in range(nvars):
                    varspec = (fp.readline(BSIZE_SP).strip()
                               .decode('ascii').split())
                    assert(varn == int(varspec[0]))
                    if(varspec[1] not in names):
                        names[varspec[1]] = 1
                    else:
                        varspec[1] += str(ind)
                        ind +=1
                    plot['varnames'].append(varspec[1])
                    plot['varunits'].append(varspec[2])
            if mdata[0].lower() == b'binary':
                rowdtype = np.dtype({'names': plot['varnames'],
                                     'formats':[np.complex128 if b'complex'
                                                 in plot[b'flags']
                                                 else np.float64]*nvars})
                arrs.append(np.fromfile(fp, dtype=rowdtype, count=npoints))
                plots.append(plot)
                fp.readline() 
        else:
            break
    fp.close()
    return (arrs, plots)

def toDataFrames(ngarr):
    (arrs, plots) = ngarr
    dfs = list()
    for i in range(0, len(plots)):
        # Fixed the index from 0 to i
        df = pd.DataFrame(data=arrs[i], columns=plots[i]['varnames'])
        dfs.append(df)
    return dfs

# ==============================================================================
# 2. USER CONFIGURATION
# ==============================================================================
# ---> TOGGLE THIS TO RUN SIMULATION OR JUST PLOT <---
RUN_SIMULATION = True

# --- 3. EXECUTION LOOP ---
if RUN_SIMULATION:
    results =[]
    os.makedirs("output_ac", exist_ok=True)

    sizes = pd.read_csv("vdd_gm_sweep_sizes.csv")
    print(sizes)
    for row in sizes.itertuples(index=False):
        VDD = row.VDD
        m_alpha = int(row.P0)
        m_beta = int(row.N1)
        m_gamma = int(row.N2)

        with open("output_ac/sweep_sizes.spi", "w") as f:
            f.write(f"* Autogenerated by Grid Search\n")
            f.write(f".param AVDD = {VDD}\n")
            f.write(f".param m_alpha = {m_alpha}\n")
            f.write(f".param m_beta = {m_beta}\n")
            f.write(f".param m_gamma = {m_gamma}\n")

        process = subprocess.run(["make", "typical"])

        # --- PARSE THE RAW FILE ---
        raw_file = "output_ac/ac_SchGtKttTtVt.raw"

        if not os.path.exists(raw_file):
            print(f"  -> Error: No raw file found.")
            continue
            
        try:
            arrs, plots = ngRawRead(raw_file)
            dfs = toDataFrames((arrs, plots))
            df = dfs[0] 
                
            # Find i(vout) or i(VOUT) column name
            ivout_col = next(col for col in df.columns if 'i(vout)' in col.lower())
                
            # Since ac sweep ends exactly at 32768 Hz, extract the last value (.iloc[-1])
            i_vout_32k_c = df[ivout_col].iloc[-1]
            i_vout_32k_r = np.real(i_vout_32k_c)
            gm = i_vout_32k_r

            results.append(gm)
            
        except Exception as e:
            print(f"  -> Error parsing data: {e}")

    print(results)


    
